addSbtPlugin("com.codecommit"  % "sbt-github-packages" % "0.5.3")
addSbtPlugin("org.wartremover" % "sbt-wartremover"     % "3.0.5")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.15.2")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.15")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"       % "1.9.3")
