addSbtPlugin("com.codecommit"               % "sbt-github-packages"  % "0.5.3")
addSbtPlugin("org.wartremover"              % "sbt-wartremover"      % "3.0.8")
addSbtPlugin("org.scalameta"                % "sbt-scalafmt"         % "2.5.0")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.16.8")
addSbtPlugin("com.typesafe.play"            % "sbt-plugin"           % "2.8.18")
addSbtPlugin("org.scoverage"                % "sbt-scoverage"        % "1.9.3")
